CREATE SCHEMA IF NOT EXISTS BACKEND_SCHEMA;

CREATE SCHEMA IF NOT EXISTS POLICY_SCHEMA;

CREATE SEQUENCE IF NOT EXISTS SEQ_LEGAL_BASIS;

CREATE SEQUENCE IF NOT EXISTS SEQ_POLICY;

CREATE SEQUENCE IF NOT EXISTS SEQ_PURPOSE;

CREATE TABLE IF NOT EXISTS LEGAL_BASIS (
    LEGAL_BASIS_ID INTEGER DEFAULT NEXTVAL('SEQ_LEGAL_BASIS') PRIMARY KEY,
    DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS PURPOSE (
    PURPOSE_ID INTEGER DEFAULT NEXTVAL('SEQ_PURPOSE') PRIMARY KEY,
    PURPOSE_CODE VARCHAR(10) CONSTRAINT UK_PURPOSE_CODE UNIQUE,
    DESCRIPTION VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS BACKEND_SCHEMA.INFORMATION_TYPE (
    INFORMATION_TYPE_ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL CONSTRAINT UK_INFORATION_TYPE UNIQUE,
    DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS POLICY (
    POLICY_ID INTEGER DEFAULT NEXTVAL('SEQ_POLICY') PRIMARY KEY,
    INFORMATION_TYPE_ID INTEGER NOT NULL,
    PURPOSE_ID INTEGER NOT NULL,
    LEGAL_BASIS_ID INTEGER NOT NULL,
    LEGAL_BASIS_DESCRIPTION TEXT,
    CONSTRAINT FK_POLICY_PURPOSE FOREIGN KEY (purpose_id)
        REFERENCES PURPOSE (purpose_id),
    CONSTRAINT FK_POLICY_LEGAL_BASIS FOREIGN KEY (legal_basis_id)
        REFERENCES LEGAL_BASIS (legal_basis_id),
    CONSTRAINT FK_POLICY_INFORMATION_TYPE FOREIGN KEY (information_type_id)
        REFERENCES BACKEND_SCHEMA.INFORMATION_TYPE (information_type_id));

