CREATE SCHEMA IF NOT EXISTS BACKEND_SCHEMA;

CREATE SCHEMA IF NOT EXISTS POLICY_SCHEMA;

CREATE SEQUENCE SEQ_LEGAL_BASIS;

CREATE SEQUENCE SEQ_POLICY;

CREATE SEQUENCE SEQ_PURPOSE;

CREATE TABLE IF NOT EXISTS LEGAL_BASIS (
    legal_basis_id INTEGER DEFAULT nextval('SEQ_LEGAL_BASIS') PRIMARY KEY,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS PURPOSE (
    purpose_id INTEGER DEFAULT nextval('SEQ_PURPOSE') PRIMARY KEY,
    purpose_code VARCHAR(10) CONSTRAINT UK_PURPOSE_CODE UNIQUE,
    description VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS BACKEND_SCHEMA.INFORMATION_TYPE (
    information_type_id INTEGER NOT NULL,
    name varchar(100) not null CONSTRAINT UK_INFORMATION_NAME UNIQUE,
    description text
);

CREATE TABLE IF NOT EXISTS POLICY (
    policy_id INTEGER DEFAULT nextval('SEQ_POLICY') PRIMARY KEY,
    information_type_id INTEGER NOT NULL,
    purpose_id INTEGER NOT NULL,
    legal_basis_id INTEGER NOT NULL,
    legal_basis_description TEXT,
    CONSTRAINT FK_POLICY_PURPOSE FOREIGN KEY (purpose_id)
        REFERENCES PURPOSE (purpose_id),
    CONSTRAINT FK_POLICY_LEGAL_BASIS FOREIGN KEY (legal_basis_id)
        REFERENCES LEGAL_BASIS (legal_basis_id),
    CONSTRAINT FK_POLICY_INFORMATION_TYPE FOREIGN KEY (information_type_id)
        REFERENCES BACKEND_SCHEMA.INFORMATION_TYPE (information_type_id)
);

