apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: data-catalog-policies
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - "https://datakatalog.nais.oera-q.local/policies"
    - "https://datakatalog-q0.nav.no/policies"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: policies/internal/isAlive
    initialDelay: 60
  readiness:
    path: policies/internal/isReady
    initialDelay: 60
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      memory: 528Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: policies/internal/metrics
