version: 2.1
orbs:
  nais: navikt/nais-deployment@1.1.1
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/policies_wf
    steps:
      - checkout
      - restore_cache:
          key: policies_wf-{{ checksum "pom.xml" }}
      - run:
          name: Install java11 and build
          command: |
            sudo apt install openjdk-11-jdk
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            mvn --version
            mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: policies_wf-{{ checksum "pom.xml" }}
      - nais/docker-deploy:
          image: navikt/data-catalog-policies
  push:
    working_directory: ~/policies_wf
    docker:
      - image: circleci/openjdk:11.0.3-stretch
    steps:
      - nais/docker-deploy:
          image: navikt/data-catalog-policies
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: NAIS deployment
      - push:
          context: NAIS deployment
          requires:
            - build
      - nais/deploy:
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-policies
          image: navikt/data-catalog-policies
          github-app-id: 26100
          nais-template: naiserator.yaml
          environment: dev-sbs
          team: teamdatajegerne
          requires:
            - build
          filters:
            branches:
              only:
                - master